### ISSUE TITLE
Control panel is hidden

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#18] opened 2015-08-10 09:47 UTC
If to play in game and win, answer "Choose..." in Congratulations window, press Cancel button, then Control panel is hidden.

**Comment by kaa-ching** [comment] 2015-08-10 19:23
confirmed.

**Comment by kaa-ching** [comment] 2015-08-10 19:51
Technically, I'd think that at that point the "Congratulations" window should return... 
However, that's not technically feasible.
The whole dialog animation is a mess - different windows own the various dialogs. Whilst there is a centralized mechanism to ensure there's only one active at a time, there is no state kept. So no "switch to previous dialog" option.

What *should* be possible, is to always have controls visible when there's no dialog. And when a user has played a level more than once, we could add a "eject" button to the controls to load a new level.

Would that work?

**Comment by glixx** [comment] 2015-08-10 20:02
> Technically, I'd think that at that point the "Congratulations" window should return... 

Yes. If return is not feasible, then create "Congratulations" window again.

**Comment by kaa-ching** [comment] 2015-08-11 15:08
No, it's not possible to make a dialog return - they are killed. And no log is kept of the history, so recreating a dialog is impossible because you don't know what to recreate. That's why I came up with the addition of a "eject" or "load" button in the controls.

**Comment by glixx** [comment] 2015-08-11 20:52
I don't like idea with new button. It should be easier for users. They are children. If no history, then to implement - to add global variable for saving important info.

**Comment by kaa-ching** [comment] 2015-09-05 19:42
And 1b635e5 would close this issue... 
BUT...

I'm not happy with the current position of the 'open' button.
I also want a skip button in the UI and a button to get the gameresources panel back.
Probably will put those three together below the toolbox.

**Comment by kaa-ching** [comment] 2015-09-06 08:25
pfff, almost done... Now hook up the game resources panel.
-> add the 'skip' and 'hint' buttons there?

**Comment by kaa-ching** [comment] 2015-09-06 08:45
aaaand... we're done!

**Closed by kaa-ching** 2015-09-06 08:45 UTC
Labels: bug
