### ISSUE TITLE
Level editor toolbar looks horrible when docked left or right

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#107] opened 2016-01-30 19:57 UTC
You can grab the toolbar (hold left mouse button on that leftmost “thingie”) and move it around in 059c9776d8862d1ad37430df150103c795382851.
It is possible to dock it to the left/right/top/bottom,  but if you choose to dock it at either the left or the right, the toolbar looks seriously messed up:

https://i.imgur.com/Vx6cwFx.png

The bug does not seem to occour always, but the weird colors change as I scale the window.

The top and bottom docking positions work fine.

Tested under GNU/Linux.

**Comment by kaa-ching** [comment] 2016-01-31 21:52
This looks like a bug in Qt to me. We checked on 3 machines and couldn't reproduce the issue.

But commit bf0c455 removes the move option altogether, so this is no longer an issue. Closing as 'wontfix'

**Closed by kaa-ching** 2016-01-31 21:52 UTC
